version: "3.4"

services:

  bootnode:
    image: rupaya/bootnode:stable
    volumes:
      - bootnode:/rupaya
    ports:
      - target: 30301
        published: 30301
        protocol: tcp
        mode: host
      - target: 30301
        published: 30301
        protocol: udp
        mode: host
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.labels.bootnode == true

volumes:
  bootnode:
