version: "3.4"

services:

  masternode_rupaya01:
    image: rupaya/node:stable
    environment:
      IDENTITY: rupaya01
      PASSWORD_FILE: /run/secrets/rupaya_password_rupaya01
      PRIVATE_KEY_FILE: /run/secrets/rupaya_pk_rupaya01
      BOOTNODES: enode://daea23c08fc591109d1478543ed06fc714bd2b380c1eb4bc81e0d0e2ce75d900cfa8010fe127028366c4d8ff5e132246a6268a884152785946c4d13dccf2980e@206.189.18.217:30301
      NETWORK_ID: 88
      VERBOSITY: 3
      NETSTATS_HOST: stats.rupaya.io
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
      ANNOUNCE_TXS: 'true'
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - target: 7050
        published: 7050
        protocol: tcp
        mode: host
      - target: 8050
        published: 8050
        protocol: tcp
        mode: host
    secrets:
      - rupaya_password_rupaya01
      - rupaya_pk_rupaya01
      - netstats_ws_secret
    volumes:
      - /mnt/sgp1_vol_mainnet_masternode01_chaindata/data:/rupaya/data
    deploy:
      placement:
        constraints:
          - node.labels.project == masternode
          - node.labels.masternode == rupaya01

  masternode_rupaya02:
    image: rupaya/node:stable
    environment:
      IDENTITY: rupaya02
      PASSWORD_FILE: /run/secrets/rupaya_password_rupaya02
      PRIVATE_KEY_FILE: /run/secrets/rupaya_pk_rupaya02
      BOOTNODES: enode://daea23c08fc591109d1478543ed06fc714bd2b380c1eb4bc81e0d0e2ce75d900cfa8010fe127028366c4d8ff5e132246a6268a884152785946c4d13dccf2980e@206.189.18.217:30301
      NETWORK_ID: 88
      VERBOSITY: 3
      NETSTATS_HOST: stats.rupaya.io
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
      ANNOUNCE_TXS: 'true'
      MAXPEERS: 200
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - target: 7050
        published: 7050
        protocol: tcp
        mode: host
      - target: 8050
        published: 8050
        protocol: tcp
        mode: host
    secrets:
      - rupaya_password_rupaya02
      - rupaya_pk_rupaya02
      - netstats_ws_secret
    volumes:
      - /mnt/sgp1_vol_mainnet_masternode02_chaindata/data:/rupaya/data
    deploy:
      placement:
        constraints:
          - node.labels.project == masternode
          - node.labels.masternode == rupaya02

  masternode_rupaya03:
    image: rupaya/node:stable
    environment:
      IDENTITY: rupaya03
      PASSWORD_FILE: /run/secrets/rupaya_password_rupaya03
      PRIVATE_KEY_FILE: /run/secrets/rupaya_pk_rupaya03
      BOOTNODES: enode://daea23c08fc591109d1478543ed06fc714bd2b380c1eb4bc81e0d0e2ce75d900cfa8010fe127028366c4d8ff5e132246a6268a884152785946c4d13dccf2980e@206.189.18.217:30301
      NETWORK_ID: 88
      VERBOSITY: 3
      NETSTATS_HOST: stats.rupaya.io
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
      ANNOUNCE_TXS: 'true'
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - target: 7050
        published: 7050
        protocol: tcp
        mode: host
      - target: 8050
        published: 8050
        protocol: tcp
        mode: host
    secrets:
      - rupaya_password_rupaya03
      - rupaya_pk_rupaya03
      - netstats_ws_secret
    volumes:
      - /mnt/sgp1_vol_mainnet_masternode03_chaindata/data:/rupaya/data
    deploy:
      placement:
        constraints:
          - node.labels.project == masternode
          - node.labels.masternode == rupaya03

secrets:
  rupaya_password_rupaya01:
    external: true
  rupaya_pk_rupaya01:
    external: true
  rupaya_password_rupaya02:
    external: true
  rupaya_pk_rupaya02:
    external: true
  rupaya_password_rupaya03:
    external: true
  rupaya_pk_rupaya03:
    external: true

  netstats_ws_secret:
    external: true
