version: "3.4"

services:

  fullnode_tomoscan01:
    image: rupaya/node:stable
    environment:
      IDENTITY: tomoscan01
      BOOTNODES: enode://daea23c08fc591109d1478543ed06fc714bd2b380c1eb4bc81e0d0e2ce75d900cfa8010fe127028366c4d8ff5e132246a6268a884152785946c4d13dccf2980e@206.189.18.217:30301
      NETWORK_ID: 88
      VERBOSITY: 4
      NETSTATS_HOST: stats.rupaya.io
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
      STORE_REWARD: 'true'
      ANNOUNCE_TXS: 'true'
      DEBUG_MODE: 'true'
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - target: 7050
        published: 7050
        protocol: tcp
        mode: host
      - target: 8050
        published: 8050
        protocol: tcp
        mode: host
    secrets:
      - netstats_ws_secret
    volumes:
      - sgp1-vol-mainnet-tomoscan01-chaindata:/rupaya/data
    deploy:
      placement:
        constraints:
          - node.labels.project == fullnode
          - node.labels.fullnode == tomoscan01

  fullnode_tomoscan02:
    image: rupaya/node:stable
    environment:
      IDENTITY: tomoscan02
      BOOTNODES: enode://daea23c08fc591109d1478543ed06fc714bd2b380c1eb4bc81e0d0e2ce75d900cfa8010fe127028366c4d8ff5e132246a6268a884152785946c4d13dccf2980e@206.189.18.217:30301
      NETWORK_ID: 88
      VERBOSITY: 1
      NETSTATS_HOST: stats.rupaya.io
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
      STORE_REWARD: 'true'
      ANNOUNCE_TXS: 'true'
      DEBUG_MODE: 'true'
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - target: 7050
        published: 7050
        protocol: tcp
        mode: host
      - target: 8050
        published: 8050
        protocol: tcp
        mode: host
    secrets:
      - netstats_ws_secret
    volumes:
      - sgp1-vol-mainnet-tomoscan02-chaindata:/rupaya/data
    deploy:
      placement:
        constraints:
          - node.labels.project == fullnode
          - node.labels.fullnode == tomoscan02

secrets:
  netstats_ws_secret:
    external: true

volumes:
  sgp1-vol-mainnet-tomoscan01-chaindata:
    external: true
  sgp1-vol-mainnet-tomoscan02-chaindata:
    external: true
