version: "3.4"

services:

  fullnode_tomoscan01:
    image: rupaya/node
    environment:
      IDENTITY: tomoscan01
      BOOTNODES: enode://bd3849fffecd7d170e9f478a87f26e45e2b865392a38d7f7499aac015bce7dd6859b0016b413fca69f5968ac446906af6b8271c5f2f2b415e6ef0d5306ee979f@178.62.75.162:30301,enode://4847c3cd11d1b27b1c403aecd0fac323cc85477413a731e01de66ace162c8312a9effc013b8afc091d801ceb65cd43975543d42b4fdf9ed3f5defdbbad6aa821@68.183.38.129:30301,enode://ce238e7f2269395159ae9253f38e3f6150e6f0f3e6bf9cdc21bb0c092f24cdf5ea9b3514b1f2664f4dfcf20beae467d847df8f96ef6f45b20ff378e4790a22f8@64.227.42.139:30301
      NETWORK_ID: 77
      VERBOSITY: 4
      NETSTATS_HOST: stats.rupaya.io
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
      STORE_REWARD: 'true'
      ANNOUNCE_TXS: 'true'
      DEBUG_MODE: 'true'
    ports:
      - target: 9050
        published: 9050
        protocol: tcp
        mode: host
      - target: 9050
        published: 9050
        protocol: udp
        mode: host
      - target: 7050
        published: 7050
        protocol: tcp
        mode: host
      - target: 8050
        published: 8050
        protocol: tcp
        mode: host
    secrets:
      - netstats_ws_secret
    volumes:
      - sgp1-vol-mainnet-tomoscan01-chaindata:/rupaya/data
    deploy:
      placement:
        constraints:
          - node.labels.project == fullnode
          - node.labels.fullnode == tomoscan01

  fullnode_tomoscan02:
    image: rupaya/node
    environment:
      IDENTITY: tomoscan02
      BOOTNODES: enode://bd3849fffecd7d170e9f478a87f26e45e2b865392a38d7f7499aac015bce7dd6859b0016b413fca69f5968ac446906af6b8271c5f2f2b415e6ef0d5306ee979f@178.62.75.162:30301,enode://4847c3cd11d1b27b1c403aecd0fac323cc85477413a731e01de66ace162c8312a9effc013b8afc091d801ceb65cd43975543d42b4fdf9ed3f5defdbbad6aa821@68.183.38.129:30301,enode://ce238e7f2269395159ae9253f38e3f6150e6f0f3e6bf9cdc21bb0c092f24cdf5ea9b3514b1f2664f4dfcf20beae467d847df8f96ef6f45b20ff378e4790a22f8@64.227.42.139:30301
      NETWORK_ID: 77
      VERBOSITY: 1
      NETSTATS_HOST: stats.rupaya.io
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
      STORE_REWARD: 'true'
      ANNOUNCE_TXS: 'true'
      DEBUG_MODE: 'true'
    ports:
      - target: 9050
        published: 9050
        protocol: tcp
        mode: host
      - target: 9050
        published: 9050
        protocol: udp
        mode: host
      - target: 7050
        published: 7050
        protocol: tcp
        mode: host
      - target: 8050
        published: 8050
        protocol: tcp
        mode: host
    secrets:
      - netstats_ws_secret
    volumes:
      - sgp1-vol-mainnet-tomoscan02-chaindata:/rupaya/data
    deploy:
      placement:
        constraints:
          - node.labels.project == fullnode
          - node.labels.fullnode == tomoscan02

secrets:
  netstats_ws_secret:
    external: true

volumes:
  sgp1-vol-mainnet-tomoscan01-chaindata:
    external: true
  sgp1-vol-mainnet-tomoscan02-chaindata:
    external: true
