version: "3.4"

services:

  node:
    image: rupaya/node
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      IDENTITY: $IDENTITY
      PRIVATE_KEY: $PRIVATE_KEY
      BOOTNODES: enode://bd3849fffecd7d170e9f478a87f26e45e2b865392a38d7f7499aac015bce7dd6859b0016b413fca69f5968ac446906af6b8271c5f2f2b415e6ef0d5306ee979f@178.62.75.162:30301,enode://4847c3cd11d1b27b1c403aecd0fac323cc85477413a731e01de66ace162c8312a9effc013b8afc091d801ceb65cd43975543d42b4fdf9ed3f5defdbbad6aa821@68.183.38.129:30301,enode://ce238e7f2269395159ae9253f38e3f6150e6f0f3e6bf9cdc21bb0c092f24cdf5ea9b3514b1f2664f4dfcf20beae467d847df8f96ef6f45b20ff378e4790a22f8@64.227.42.139:30301
      NETWORK_ID: 77
      VERBOSITY: 3
      NETSTATS_HOST: stats.rupaya.io
      NETSTATS_PORT: 443
      WS_SECRET: universal-gas-lighter-refill
    volumes:
      - $DATA:/rupaya/data/rupx/chaindata
    networks:
      - masternode
    ports:
      - 9050:9050/tcp
      - 9050:9050/udp
    labels:
      - traefik.rpc.backend=rpc
      - traefik.rpc.frontend.rule=Host:socket.rupaya.io
      - traefik.rpc.docker.network=masternode
      - traefik.rpc.port=7050
      - traefik.ws.backend=websocket
      - traefik.ws.frontend.rule=Host:ws.rupaya.io
      - traefik.ws.docker.network=masternode
      - traefik.ws.port=8050
      - traefik.ws.loadbalancer.stickiness=true
    restart: always

  proxy:
    image: traefik:alpine
    environment:
      CF_API_EMAIL: $CLOUDFLARE_EMAIL
      CF_API_KEY: $CLOUDFLARE_API_KEY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./acme.json:/acme.json:rw
      - ./traefik.toml:/traefik.toml:ro
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    networks:
      - masternode
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.enable=false

networks:
  masternode:
