defaultEntryPoints = ["http", "https"]

[accessLog]

[entryPoints]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[acme]
email = "aasim@rupx.io"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 5

[docker]
domain = "rupaya.io"
watch = true
network = "masternode"
